version: '2'

services:
    frontend:
        labels:
            com.desdulianto.description: "nginx frontend"
        image: nginx:alpine
        ports:
            - "80:80"
            - "443:443"
        volumes:
            #- ./nginx.conf:/etc/nginx/nginx.conf:ro
            - ./default.conf:/etc/nginx/conf.d/default.conf:ro
            - ./public_html:/var/www/html:ro
            - ./logs:/var/log/nginx
        networks:
            - teaching

    backend:
        build: .
        labels:
            com.desdulianto.description: "php-fpm dengan tambahan module mysql"
        ports:
            - "9000:9000"
        volumes:
            - ./public_html:/var/www/html
            - ./www.conf:/etc/php5/fpm/pool.d/www-cust.conf
        networks:
            - teaching
    
    db:
        image: mysql
        ports:
            - "3306:3306"
        volumes:
            - ./db:/var/lib/mysql
        environment:
            MYSQL_DATABASE: web
            MYSQL_USER: web
            MYSQL_PASSWORD: web
            MYSQL_ROOT_PASSWORD: teachphp
        networks:
            - teaching

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - "8080:80"
        environment:
            PMA_HOST: db
            MYSQL_ROOT_PASSWORD: teachphp
        networks:
            - teaching

networks:
    teaching:
